# General configuration of the Prefix installation,
# for instance locale support.
---

- name: Add locales to configuration file
  ansible.builtin.lineinfile:
    path: "{{ gentoo_prefix_path }}/etc/locale.gen"
    line: "{{ item }}"
    state: present
  with_items: "{{ prefix_locales }}"
  notify: Generate locales

- name: Check which GCC versions are available
  ansible.builtin.command: "{{ gentoo_prefix_path }}/usr/bin/gcc-config --list-profiles"

- name: Check which GCC version is configured
  ansible.builtin.command: "{{ gentoo_prefix_path }}/usr/bin/gcc-config --get-current-profile"

- name: Print current GCC environment
  ansible.builtin.command: "{{ gentoo_prefix_path }}/usr/bin/gcc-config --print-environ"

# Set default compiler in compat layer.
# We should not use the latest version of GCC here, since that will probably cause problems
# when building older GCC versions with EasyBuild in the software layer.
# (see https://github.com/EESSI/software-layer/issues/151).
# Note: the selected GCC version must be installed (cfr. EESSI set in gentoo-overlay)
- name: Make specific GCC version the default compiler
  ansible.builtin.command: "{{ gentoo_prefix_path }}/usr/bin/gcc-config {{ prefix_default_gcc }}"
  changed_when: false
